# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Configure buildscript warnings to be errors
org.gradle.kotlin.dsl.allWarningsAsErrors=true
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Metadata
mod_id=minecarttweaks
mod_display_name=Cammie's Minecart Tweaks
mod_description=Making Minecarts more viable for transportation
sources_url=https://github.com/CammiesCorner/Cammies-Minecart-Tweaks
issues_url=https://github.com/CammiesCorner/Cammies-Minecart-Tweaks/issues
license_url=https://github.com/CammiesCorner/Cammies-Minecart-Tweaks/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://cammiescorner.dev

# Publishing
group=dev.cammiescorner.minecarttweaks
curseforge_id=579937
modrinth_id=D2gIe1ZY

# Dependencies are managed at gradle/libs.versions.toml
